experiment: disentangle
run: disentangle-jtd+pijama-nomask
learning_rate: 1.0e-4
batch_size: 1
epochs: 100
train_dataset_cfg:
  n_clips: null
  normalize_velocity: True
  data_augmentation: True
  multichannel: True
test_dataset_cfg:
  n_clips: null
  normalize_velocity: True
  data_augmentation: False
  multichannel: True
encoder_module: disentangle
model_cfg:
  use_gru: True
  use_masking: False
checkpoint_cfg:
  save_checkpoints: True
  load_checkpoints: True
  checkpoint_after_n_epochs: 10
mlflow_cfg:
  use: True
  tracking_uri: http://127.0.0.1:8000