experiment: rhythm-only
run: crnn-ibn-jtd+pijama-rhythmonly
learning_rate: 1.0e-4
batch_size: 12
epochs: 100
train_dataset_cfg:
  n_clips: null
  normalize_velocity: False
  data_augmentation: False    # No need for this
  rhythm_only: True
test_dataset_cfg:
  n_clips: null
  normalize_velocity: False
  data_augmentation: False
  rhythm_only: True
encoder_module: crnn
model_cfg:
  use_ibn: True
checkpoint_cfg:
  save_checkpoints: True
  load_checkpoints: True
  checkpoint_after_n_epochs: 10
mlflow_cfg:
  use: True
  tracking_uri: http://127.0.0.1:8000