experiment: baselines
run: crnn-jtd+pijama-augment
batch_size: 20
epochs: 100
data_split_dir: 20class_80min
classify_dataset: False
train_dataset_cfg:
  n_clips: null
  normalize_velocity: True
  multichannel: False
  data_augmentation: True
  augmentation_probability: 0.5
  jitter_start: True
test_dataset_cfg:
  n_clips: null
  normalize_velocity: True
  multichannel: False
  data_augmentation: False
  jitter_start: False
encoder_module: crnn
model_cfg:
  pool_type: max
  norm_type: bn
optim_type: adam
optim_cfg:
  lr: 1.0e-3
checkpoint_cfg:
  save_checkpoints: True
  load_checkpoints: True
  checkpoint_after_n_epochs: 10
mlflow_cfg:
  use: True
  run_id: af0ff46a3162469ab7ab772daacbcbb9
  tracking_uri: http://127.0.0.1:5000