experiment: baselines
run: crnn-jtd+pijama
batch_size: 5
epochs: 100
train_dataset_cfg:
  n_clips: null
  normalize_velocity: True
  multichannel: False
  data_augmentation: False
  jitter_start: False
test_dataset_cfg:
  n_clips: null
  normalize_velocity: True
  multichannel: False
  data_augmentation: False
  jitter_start: False
encoder_module: crnn
model_cfg:
  pool_type: max
  norm_type: bn
optim_type: adam
optim_cfg:
  lr: 1.0e-3
checkpoint_cfg:
  save_checkpoints: True
  load_checkpoints: True
  checkpoint_after_n_epochs: 10
mlflow_cfg:
  use: True
  tracking_uri: http://127.0.0.1:5000