experiment: baselines
run: resnet50-jtd+pijama
learning_rate: 0.01    # NB. used SGD with momentum, weight regularisation, and LR scheduling in original paper!
batch_size: 5
epochs: 100
classify_dataset: False
train_dataset_cfg:
  n_clips: null
  normalize_velocity: True
  multichannel: False
  data_augmentation: False
  jitter_start: False
test_dataset_cfg:
  n_clips: null
  normalize_velocity: True
  multichannel: False
  data_augmentation: False
  jitter_start: False
encoder_module: resnet50
model_cfg:
  layers: [ 3, 4, 6, 3 ]
checkpoint_cfg:
  save_checkpoints: True
  load_checkpoints: True
  checkpoint_after_n_epochs: 10
mlflow_cfg:
  use: True
  tracking_uri: http://127.0.0.1:5000