experiment: default
run: debug_local
batch_size: 1
epochs: 100
classify_dataset: False
train_dataset_cfg:
  n_clips: 1
  normalize_velocity: False
test_dataset_cfg:
  n_clips: 1
  normalize_velocity: False
encoder_module: cnn
model_cfg:
  pool_type: max
  norm_type: bn
optim_type: adam
optim_cfg:
  lr: 1.0e-3
checkpoint_cfg:
  save_checkpoints: False
  load_checkpoints: False
  checkpoint_after_n_epochs: 10
mlflow_cfg:
  use: False