experiment: default
run: debug_local
learning_rate: 1.0e-3
batch_size: 1
epochs: 100
# We just use a small toy dataset for debug purposes
train_dataset_cfg:
  n_clips: 1
  normalize_velocity: False
test_dataset_cfg:
  n_clips: 1
  normalize_velocity: False
encoder_module: cnn
model_cfg:
  use_ibn: False
checkpoint_cfg:
  save_checkpoints: False
  load_checkpoints: False
  checkpoint_after_n_epochs: 10
mlflow_cfg:
  use: False
  tracking_uri: http://127.0.0.1:8080