experiment: default
run: debug_local
learning_rate: 1.0e-3
batch_size: 1
epochs: 100
# We just use a small toy dataset for debug purposes
dataset_cfg:
  train_size: 1
  test_size: 1
model_cfg:
  encoder: crnn
  has_gru: True
checkpoint_cfg:
  save_checkpoints: True
  load_checkpoints: True
  checkpoint_after_n_epochs: 10
mlflow_cfg:
  use: False
  tracking_uri: http://127.0.0.1:8080