experiment: default
run: default
learning_rate: 1.0e-3
batch_size: 12
epochs: 100
# We just use a small toy dataset for debug purposes
dataset_cfg:
  train_size: 100
  test_size: 100
encoder_module: crnn
model_cfg:
  use_ibn: False
checkpoint_cfg:
  save_checkpoints: True
  load_checkpoints: True
  checkpoint_after_n_epochs: 10
mlflow_cfg:
  use: False
  tracking_uri: http://127.0.0.1:8080